[tool.vulture]
exclude = [".vscode/"]

[tool.pylint.messages_control]
disable = [
    "missing-module-docstring",
    "missing-class-docstring",
    "missing-function-docstring",
    "too-few-public-methods",
    "protected-access"
]

[tool.pylint.format]
max-line-length = 135
